version: '3'

services:
  # app:
  #   build: .
  #   ports:
  #     - 8080:8080
  #   restart: always
  #   depends_on:
  #     - database
  #   networks:
  #     - fullstack

  database:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: service-db
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
#     networks:
#       - fullstack

# networks:
#   fullstack:
#     driver: bridge
  